#!/usr/bin/env bash
# 0-change_your_home_IP
# Script to change localhost and facebook.com resolution
# Add new entries at the end of /etc/hosts
sudo echo "127.0.0.2   localhost" >> /etc/hosts
sudo echo "8.8.8.8     facebook.com" >> /etc/hosts
