#!/usr/bin/env bash
# 1-show_attached_IPs
# Script to display all active IPv4 addresses on the machine

# Use 'ip -4' to list IPv4 addresses and filter with awk
ip -4 addr show | awk '/inet/ {print $2}' | cut -d/ -f1
